# Generated by Django 4.1 on 2022-09-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_inventory_fiyati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Stok_Tarihi',
            field=models.DateField(null=True),
        ),
    ]
