# Generated by Django 4.1 on 2022-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_kime_verilecek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Fiyati',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Stok_Durumu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Ürün_Ad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Ürün_Cinsi',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Ürün_Numarasi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
